### ISSUE TITLE
Atom type B not recognized during the OACF calculation?

### ISSUE THREAD

**Issue by Guancred** [jasiegert/traj_c#1]
Hi,
there is an error when I calculated the OACF of BH4 anions:
" 
Trajectory has been read from dat-file.
	took 0.240000 s in CPU time.
Removing com...done
oacf B H 200 0.4
	OACF calculation
	Atom type B not recognized.
	something went wrong.
"
What should i do to solve it?

**Comment by jasiegert** [comment]
Hey,

The problem was that the atomic masses of some elements were missing. I have now added support for the entire periodic table.
This repo is mostly my C playground and is technically still under development. If you're looking for a more robust solution, you could check out the program that inspired this project, [TRAVIS](http://www.travis-analyzer.de/) and its rdyn function. Otherwise feel free to pull the newest version and try again.

**Comment by Guancred** [comment]
>

**Comment by Guancred** [comment]
Thank you, sir,
I have updated the version but another error occurs:
"
Reading pbc-file...done
Trajectory has been read from dat-file.
	took 0.110000 s in CPU time.
Removing com...done
oacf O H 200 0.4
	OACF calculation
Non-orthogonal PBCs are not supported yet. Sorry!
"
interesting, it works well sometimes for the same file.

**Comment by jasiegert** [comment]
Non-orthorhombic cells were temporarily blocked by me, which slipped into the repo 3 days ago. However that restriction should have been removed the same day. The latest version should work for non-orthorhombic cells as well. I have tagged it as version 0.1.0.
On another note, the OACF so far only supports unwrapped trajectories. If your BH4 anions extend beyond the periodic boundary conditions, you could try checking out the development branch "wrapped_oacf".

If you find another problem, feel free to pass me a short part of an example trajectory and I'll have a look.
